# Site settings
title: XBILI
subtitle: Always Be Coding
email: me@xbili.com
description: > # this means to ignore newlines until "baseurl:"
  Xu Bili. Computer Science Undergraduate at National University of Singapore.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xbili.com" # the base hostname & protocol for your site
twitter_username: _xbili
github_username:  xbili
gems: [jekyll-read-more]

# Build settings
markdown: kramdown
